name: 'Research Project Action'
description: 'Create videos from webprojects'
author: 'Jonas De Meyer'
inputs:
  ffmpeg-path:
    description: 'Path to ffmpeg installation'
    required: true
  chrome-path:
    description: 'Path to chrome installation'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
