name: Project build
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          npm ci
          npm run build:dev

      - name: Checkout static html site
        uses: actions/checkout@v2
        with:
          repository: Nobilus/Tobbedansen-2020
          path: ./static

      - name: install ffmpeg
        run: |
          sudo apt-get -qq --no-install-recommends install ffmpeg

      - name: install pm2
        run: npm install pm2@latest -g

      - name: install pm2 typescript
        run: pm2 install typescript

      - name: get ffmpeg  path
        id: get-ffmpeg-path
        run: echo "::set-output name=ffmpeg::$(which ffmpeg)"

      - name: get chrome path
        id: get-chrome-path
        run: echo "::set-output name=chrome::$(which google-chrome-stable)"

      - name: change dir
        run: cd static

      - name: test the github action
        uses: ./
        with:
          ffmpeg-path: ${{steps.get-ffmpeg-path.outputs.ffmpeg}}
          chrome-path: ${{steps.get-chrome-path.outputs.chrome}}
          project-dir: ./static

      - name: update version number
        run: npm version minor
