name: Project build
on:
  push:
    branches:
      - feature/convert-to-javascript-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build the action
        run: |
          npm ci
          npm run build
      - name: Commit and push build
        continue-on-error: true
        run: |
          git config --global user.name 'Workflow-Builder'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add .
          git commit -am "Generated new build"
          git push
