name: Project build
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build the action
        run: |
          npm ci
          npm run build
      - name: Commit and push build
        run: |
          git config --global user.name 'Workflow-Builder'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add .
          git commit -am "Generated new build" || echo "No changes to commit"
          git push
      - name: Set env variables
        run: |
          echo $CREDENTIALS_FILE >> ./service-account.json
          echo BUCKET=$BUCKET >> ./.env
        shell: bash
        env:
          CREDENTIALS_FILE: ${{ secrets.GCP_CREDENTIALS }}
          BUCKET: ${{ secrets.BUCKET }}
      - name: Checkout static html site
        uses: actions/checkout@v2
        with:
          repository: Nobilus/Tobbedansen-2020
          path: ./static
      - name: install ffmpeg
        run: |
          sudo apt-get install --no-install-recommends ffmpeg
      - name: install pm2
        run: npm install pm2@latest -g
      - name: install pm2 typescript
        run: pm2 install typescript
      - name: get ffmpeg  path
        id: get-ffmpeg-path
        run: echo "::set-output name=ffmpeg::$(which ffmpeg)"
      - name: get chrome path
        id: get-chrome-path
        run: echo "::set-output name=chrome::$(which google-chrome-stable)"
      - name: list dir
        run: |
          ls -a
          cat service-account.json
      - name: change dir
        run: cd static

      - name: test the github action
        uses: ./
        with:
          ffmpeg-path: ${{steps.get-ffmpeg-path.outputs.ffmpeg}}
          chrome-path: ${{steps.get-chrome-path.outputs.chrome}}
          project-dir: ./static
