name: Project build
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build the action
        run: |
          npm ci
          npm run build
      - name: Commit and push build
        continue-on-error: true
        run: |
          git config --global user.name 'Workflow-Builder'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add dist/index.js
          git commit -am "Generated new build"
          git push

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
