name: Test action
on:
  push:
    branches:
      - feature/convert-to-javascript-action
    paths:
      - dist/**

jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
