on: [push]

jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    name: A job to checkout repo into dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: npm ci, build and test
        uses: Jonas-D-M/Research-Project@v1
        run: |
          npm ci
          npm run build --if presenst

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
     
      - name: Hello world action step
        id: hello
        uses: Jonas-D-M/Research-Project@v1
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
