name: Project build
on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build the action
        run: |
          npm ci
          npm run build

      - name: Commit and push build
        run: |
          git config --global user.name 'Workflow-Builder'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add .
          git commit -am "Generated new build" || echo "No changes to commit"
          git push

      - name: Update version number
        run: npm version major

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.package-version.outputs.current-version}}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Commit and push build
        run: |
          git config --global user.name 'Workflow-Builder'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add .
          git commit -am "Update package.json version" || echo "No changes to commit"
          git push
